-- MySQL Script generated by MySQL Workbench
-- Wed Jul 19 15:16:01 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema arkhi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema arkhi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `arkhi` DEFAULT CHARACTER SET utf8 ;
USE `arkhi` ;

-- -----------------------------------------------------
-- Table `arkhi`.`tbEditora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arkhi`.`tbEditora` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arkhi`.`tbLivro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arkhi`.`tbLivro` (
  `isbn` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `datapublicacao` DATETIME NULL,
  `preco` FLOAT NULL,
  `img` VARCHAR(45) NULL,
  `ideditora` INT NOT NULL,
  PRIMARY KEY (`isbn`),
  INDEX `fk_tbLivro_tbEditora1_idx` (`ideditora` ASC),
  CONSTRAINT `fk_tbLivro_tbEditora1`
    FOREIGN KEY (`ideditora`)
    REFERENCES `arkhi`.`tbEditora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arkhi`.`tbAutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arkhi`.`tbAutor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arkhi`.`tbCritica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arkhi`.`tbCritica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `critica` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arkhi`.`tbAutorLivro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arkhi`.`tbAutorLivro` (
  `idautor` INT NOT NULL,
  `isbn` INT NOT NULL,
  INDEX `fk_tbAutor_has_tbLivro_tbLivro1_idx` (`isbn` ASC),
  INDEX `fk_tbAutor_has_tbLivro_tbAutor_idx` (`idautor` ASC),
  PRIMARY KEY (`idautor`, `isbn`),
  CONSTRAINT `fk_tbAutor_has_tbLivro_tbAutor`
    FOREIGN KEY (`idautor`)
    REFERENCES `arkhi`.`tbAutor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbAutor_has_tbLivro_tbLivro1`
    FOREIGN KEY (`isbn`)
    REFERENCES `arkhi`.`tbLivro` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `arkhi`.`tbCriticaLivro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arkhi`.`tbCriticaLivro` (
  `idcritica` INT NOT NULL,
  `isbn` INT NOT NULL,
  PRIMARY KEY (`idcritica`, `isbn`),
  INDEX `fk_tbCritica_has_tbLivro_tbLivro1_idx` (`isbn` ASC),
  INDEX `fk_tbCritica_has_tbLivro_tbCritica1_idx` (`idcritica` ASC),
  CONSTRAINT `fk_tbCritica_has_tbLivro_tbCritica1`
    FOREIGN KEY (`idcritica`)
    REFERENCES `arkhi`.`tbCritica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbCritica_has_tbLivro_tbLivro1`
    FOREIGN KEY (`isbn`)
    REFERENCES `arkhi`.`tbLivro` (`isbn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
